import json

def apply_fixes():
    path = 'src/data/questions.json'
    with open(path, 'r', encoding='utf-8') as f:
        questions = json.load(f)

    to_delete = [
        380, 387, 445, 455, 487, 553, 554, 555, 556, 564, 567, 569, 574, 
        198, 110, 114, 242, 137, 29, 312, 354, 355, 359, 360, 369, 475, 
        350, 353, 547, 572, 109, 172
    ]

    questions = [q for q in questions if q['id'] not in to_delete]

    overrides = [
        {"id": 71, "category": "quran", "question": {"es": "¿Cuántos libros sagrados se mencionan por nombre en el Corán?", "en": "How many sacred books are mentioned by name in the Quran?", "ma": "شحال من كتاب مقدس تذكر بالاسم فالقرآن؟"}, "options": {"es": ["2", "3", "4 principales (con alusión a las Suhuf)", "6"], "en": ["2", "3", "4 main ones (with allusion to the Suhuf)", "6"], "ma": ["2", "3", "4 رئيسين (مع الإشارة للصحف)", "6"]}, "correct_answer": {"es": "4 principales (con alusión a las Suhuf)", "en": "4 main ones (with allusion to the Suhuf)", "ma": "4 رئيسين (مع الإشارة للصحف)"}, "difficulty": "medium", "explanation": {"es": "Tawrah, Zabur, Injil y Corán. Suhuf de Ibrahim y Musa.", "en": "Tawrah, Zabur, Injil, and Quran.", "ma": "التوراة الزبور الإنجيل و القرآن."}},
        {"id": 178, "category": "prophets", "question": {"es": "¿Cuál fue el destino de la esposa del Profeta Lut?", "en": "What was the fate of Prophet Lut's wife?", "ma": "شنو كان مصير زوجة النبي لوط؟"}, "options": {"es": ["Se salvó con él", "Se quedó atrás y fue destruida junto con la ciudad", "Murió de enfermedad", "Fue capturada"], "en": ["She was saved with him", "She stayed behind and was destroyed along with the city", "Died of illness", "Was captured"], "ma": ["نجات معاه", "بقات للور وتهلكات مع المدينة", "ماتت بالمرض", "تأسرات"]}, "correct_answer": {"es": "Se quedó atrás y fue destruida junto con la ciudad", "en": "She stayed behind and was destroyed along with the city", "ma": "بقات للور وتهلكات مع المدينة"}, "difficulty": "medium", "explanation": {"es": "Corán 11:81; 66:10", "en": "Quran 11:81; 66:10", "ma": "القرآن 11:81؛ 66:10"}},
        {"id": 188, "category": "prophets", "question": {"es": "¿Qarun de quién era contemporáneo?", "en": "Qarun was a contemporary of whom?", "ma": "قارون شكون عاصر؟"}, "options": {"es": ["De Nuh", "Del Profeta Musa", "De Ibrahim", "De Dawud"], "en": ["Of Nuh", "Of Prophet Musa", "Of Ibrahim", "Of Dawud"], "ma": ["نوح", "النبي موسى", "إبراهيم", "داود"]}, "correct_answer": {"es": "Del Profeta Musa", "en": "Of Prophet Musa", "ma": "النبي موسى"}, "difficulty": "medium", "explanation": {"es": "Qarun, arrogante por riqueza. (Corán 28:76-82)", "en": "Quran 28:76-82", "ma": "القرآن 28:76-82"}},
        {"id": 285, "category": "seerah", "question": {"es": "¿Cuántas esposas tuvo el Profeta Muhammad (ﷺ) en total durante su vida?", "en": "How many wives did Prophet Muhammad (ﷺ) have?", "ma": "شحال من زوجة كانت عند النبي محمد (ﷺ)؟"}, "options": {"es": ["4", "9", "11", "13"], "en": ["4", "9", "11", "13"], "ma": ["4", "9", "11", "13"]}, "correct_answer": {"es": "11", "en": "11", "ma": "11"}, "difficulty": "medium", "explanation": {"es": "Tuvo 11 en total, 9 al morir.", "en": "11 wives in total, 9 upon death.", "ma": "كان عندو 11 زوجة."}},
        {"id": 133, "category": "seerah", "question": {"es": "¿Cuál es el término árabe para la biografía del Profeta Muhammad (ﷺ)?", "en": "Term for biography of Prophet Muhammad?", "ma": "شنو المصطلح لسيرة النبي محمد؟"}, "options": {"es": ["Tafsir", "Hadith", "Seerah", "Aqida"], "en": ["Tafsir", "Hadith", "Seerah", "Aqida"], "ma": ["تفسير", "حديث", "سيرة", "عقيدة"]}, "correct_answer": {"es": "Seerah", "en": "Seerah", "ma": "سيرة"}, "difficulty": "medium", "explanation": {"es": "La Seerah es la biografía del Profeta.", "en": "Seerah is biography.", "ma": "السيرة هي قصة حياة النبي."}},
        {"id": 134, "category": "quran", "question": {"es": "¿Qué es el 'Witr' en la práctica islámica?", "en": "What is 'Witr'?", "ma": "شنو هو الوتر؟"}, "options": {"es": ["Un mes islámico", "Una oración de número impar de rak'at al final de la noche", "Una forma de ayuno", "Un tipo de caridad"], "en": ["Month", "Odd number prayer", "Fast", "Charity"], "ma": ["شهر", "صلاة بعدد فردي للركعات", "صيام", "صدقة"]}, "correct_answer": {"es": "Una oración de número impar de rak'at al final de la noche", "en": "Odd number prayer", "ma": "صلاة بعدد فردي للركعات"}, "difficulty": "medium", "explanation": {"es": "Cierra las oraciones nocturnas.", "en": "Closes night prayers.", "ma": "كتختم صلوات الليل."}},
        {"id": 135, "category": "quran", "question": {"es": "¿Cuál es el término para el sermón del viernes?", "en": "Friday sermon?", "ma": "خطبة الجمعة؟"}, "options": {"es": ["Adhan", "Iqama", "Khutbah", "Wa'dh"], "en": ["Adhan", "Iqama", "Khutbah", "Wa'dh"], "ma": ["أذان", "إقامة", "خطبة", "وعظ"]}, "correct_answer": {"es": "Khutbah", "en": "Khutbah", "ma": "خطبة"}, "difficulty": "medium", "explanation": {"es": "El sermón dado antes del Jumu'ah.", "en": "Given before Friday prayer.", "ma": "قبل صلاة الجمعة."}},
        {"id": 197, "category": "prophets", "question": {"es": "¿Cuál fue la súplica del Profeta Ayyub mencionada en el Corán?", "en": "Supplication of Ayyub?", "ma": "دعاء أيوب؟"}, "options": {"es": ["La ilaha illa anta...", "Que me ha tocado la adversidad, y Tú eres el más misericordioso...", "Rabbana atina...", "Hasbunallahu..."], "en": ["La ilaha illa...", "Adversity has touched me and You are the most Merciful...", "Rabbana...", "Hasbunallahu..."], "ma": ["لا إله إلا...", "أني مسني الضر وأنت أرحم الراحمين", "ربنا...", "حسبنا..."]}, "correct_answer": {"es": "Que me ha tocado la adversidad, y Tú eres el más misericordioso...", "en": "Adversity has touched me and You are the most Merciful...", "ma": "أني مسني الضر وأنت أرحم الراحمين"}, "difficulty": "medium", "explanation": {"es": "Corán 21:83", "en": "Quran 21:83", "ma": "21:83"}},
        {"id": 200, "category": "prophets", "question": {"es": "¿En qué tierra se estableció el Profeta Musa tras huir de Egipto?", "en": "Land Musa fled to?", "ma": "فين استقر موسى؟"}, "options": {"es": ["Sham (Siria)", "Madián", "Canaán", "Babilonia"], "en": ["Syria", "Midian", "Canaan", "Babylon"], "ma": ["الشام", "مدين", "كنعان", "بابل"]}, "correct_answer": {"es": "Madián", "en": "Midian", "ma": "مدين"}, "difficulty": "medium", "explanation": {"es": "Corán 28:22", "en": "Quran 28:22", "ma": "28:22"}},
        {"id": 201, "category": "prophets", "question": {"es": "¿Cuántos profetas del Corán son de la descendencia de Ibrahim?", "en": "How many prophets are from Ibrahim?", "ma": "شحال من نبي من ذرية إبراهيم؟"}, "options": {"es": ["Ninguno", "5", "La mayoría de los profetas posteriores...", "Solo 2"], "en": ["None", "5", "Majority of later prophets", "Only 2"], "ma": ["0", "5", "أغلبية الأنبياء لي من بعد", "2"]}, "correct_answer": {"es": "La mayoría de los profetas posteriores...", "en": "Majority of later prophets", "ma": "أغلبية الأنبياء لي من بعد"}, "difficulty": "medium", "explanation": {"es": "Corán 6:84", "en": "Quran 6:84", "ma": "6:84"}},
        {"id": 301, "category": "seerah", "question": {"es": "¿Cuál fue la importancia del Isra wal-Mi'raj?", "en": "Importance of Isra wal Mi'raj?", "ma": "أهمية الإسراء والمعراج؟"}, "options": {"es": ["Revelación Corán", "Fue cuando se prescribieron las cinco oraciones", "Primera batalla", "Establecimiento Qibla"], "en": ["Quran revealed", "Five daily prayers prescribed", "First battle", "Qibla set"], "ma": ["نزل القرآن", "تفرضو الصلوات الخمس", "أول غزوة", "تحددات القبلة"]}, "correct_answer": {"es": "Fue cuando se prescribieron las cinco oraciones", "en": "Five daily prayers prescribed", "ma": "تفرضو الصلوات الخمس"}, "difficulty": "medium", "explanation": {"es": "Se prescribieron oraciones.", "en": "Prayers prescribed.", "ma": "الصلوات."}},
        {"id": 302, "category": "seerah", "question": {"es": "¿Batalla que permitió conquistar Siria?", "en": "Battle that conquered Syria?", "ma": "غزوة فتح الشام؟"}, "options": {"es": ["Qadisiyyah", "Batalla de Yarmuk", "Nahawand", "Ajnadain"], "en": ["Qadisiyyah", "Yarmouk", "Nahawand", "Ajnadain"], "ma": ["القادسية", "اليرموك", "نهاوند", "أجنادين"]}, "correct_answer": {"es": "Batalla de Yarmuk", "en": "Yarmouk", "ma": "اليرموك"}, "difficulty": "medium", "explanation": {"es": "Contra el imperio Bizantino.", "en": "Against Byzantine empire.", "ma": "ضد البيزنطيين."}},
        {"id": 303, "category": "seerah", "question": {"es": "¿Batalla que destruyó al Imperio Sasánida?", "en": "Battle that destroyed Sassanid Empire?", "ma": "غزوة دمرات الإمبراطورية الساسانية؟"}, "options": {"es": ["Yarmuk", "Batalla de Qadisiyyah", "Nahawand", "Ajnadain"], "en": ["Yarmouk", "Qadisiyyah", "Nahawand", "Ajnadain"], "ma": ["اليرموك", "القادسية", "نهاوند", "أجنادين"]}, "correct_answer": {"es": "Batalla de Qadisiyyah", "en": "Qadisiyyah", "ma": "القادسية"}, "difficulty": "medium", "explanation": {"es": "Comandó Sa'ad ibn Abi Waqqas.", "en": "Sa'ad commander.", "ma": "سعد بن أبي وقاص قائد."}},
        {"id": 304, "category": "seerah", "question": {"es": "¿Primera expedición militar de musulmanes?", "en": "First military expedition?", "ma": "أول سرية عسكرية؟"}, "options": {"es": ["Batalla de Badr", "Expedición de Hamza ibn Abd al-Muttalib", "Uhud", "Khandaq"], "en": ["Badr", "Hamza expedition", "Uhud", "Khandaq"], "ma": ["بدر", "سرية حمزة", "أحد", "الخندق"]}, "correct_answer": {"es": "Expedición de Hamza ibn Abd al-Muttalib", "en": "Hamza expedition", "ma": "سرية حمزة"}, "difficulty": "medium", "explanation": {"es": "Sariyyat al-Kharrar", "en": "Sariyyat al-Kharrar.", "ma": "سرية الخرار."}},
        {"id": 305, "category": "seerah", "question": {"es": "¿Primer esclavo en abrazar el Islam?", "en": "First slave to embrace Islam?", "ma": "أول عبد أسلم؟"}, "options": {"es": ["Zayd ibn Harithah", "Bilal ibn Rabah", "Ammar ibn Yasir", "Suhayb"], "en": ["Zayd ibn Harithah", "Bilal", "Ammar", "Suhayb"], "ma": ["زيد بن حارثة", "بلال", "عمار", "صهيب"]}, "correct_answer": {"es": "Zayd ibn Harithah", "en": "Zayd ibn Harithah", "ma": "زيد بن حارثة"}, "difficulty": "medium", "explanation": {"es": "Zayd fue el primero, antes que Bilal.", "en": "Zayd was first.", "ma": "زيد الأول."}},
        {"id": 306, "category": "seerah", "question": {"es": "¿Importancia estratégica de Khandaq?", "en": "Strategic importance of Khandaq?", "ma": "أهمية غزوة الخندق؟"}, "options": {"es": ["Primera batalla", "Fracaso marcó el fin del poder ofensivo qurayshita", "Conquista La Meca", "Derrota judía"], "en": ["First battle", "Ended Qurayshi offensive power", "Mecca conquered", "Jew defeat"], "ma": ["أول غزوة", "نهاية قوة الهجوم ד قريش", "فتح مكة", "هزيمة يهود"]}, "correct_answer": {"es": "Fracaso marcó el fin del poder ofensivo qurayshita", "en": "Ended Qurayshi offensive power", "ma": "نهاية قوة الهجوم ד قريش"}, "difficulty": "medium", "explanation": {"es": "Fue la última gran ofensiva de la Meca.", "en": "Last major offensive.", "ma": "آخر هجوم كبير."}},
        {"id": 307, "category": "seerah", "question": {"es": "¿Fundador de dinastía Omeya?", "en": "Founder of Umayyad dynasty?", "ma": "مؤسس السلالة الأموية؟"}, "options": {"es": ["Yazid", "Mu'awiyah ibn Abi Sufyan", "Marwan", "Abd al-Malik"], "en": ["Yazid", "Mu'awiyah", "Marwan", "Abd al-Malik"], "ma": ["يزيد", "معاوية بن أبي سفيان", "مروان", "عبد الملك"]}, "correct_answer": {"es": "Mu'awiyah ibn Abi Sufyan", "en": "Mu'awiyah", "ma": "معاوية بن أبي سفيان"}, "difficulty": "medium", "explanation": {"es": "Gobernador de Siria.", "en": "Governor of Syria.", "ma": "حاكم الشام."}},
        {"id": 308, "category": "seerah", "question": {"es": "¿Cuántos años gobernó Uthman ibn Affan?", "en": "Years Uthman ruled?", "ma": "شحال حكم عثمان؟"}, "options": {"es": ["5 años", "8 años", "12 años", "15 años"], "en": ["5", "8", "12", "15"], "ma": ["5", "8", "12", "15"]}, "correct_answer": {"es": "12 años", "en": "12", "ma": "12"}, "difficulty": "medium", "explanation": {"es": "12 años gobernó.", "en": "12 years.", "ma": "12 عام."}},
        {"id": 309, "category": "seerah", "question": {"es": "¿Importancia de Badr?", "en": "Importance of Badr?", "ma": "أهمية غزوة بدر؟"}, "options": {"es": ["Conquista La Meca", "Primera victoria militar de musulmanes sobre líderes Quraysh", "Derrota musulmán", "Conquista Arabia"], "en": ["Conquest Mecca", "First victory over Quraysh", "Muslim defeat", "Conquest Arabia"], "ma": ["فتح مكة", "أول انتصار على قريش", "هزيمة المسلمين", "فتح العرب"]}, "correct_answer": {"es": "Primera victoria militar de musulmanes sobre líderes Quraysh", "en": "First victory over Quraysh", "ma": "أول انتصار على قريش"}, "difficulty": "medium", "explanation": {"es": "Autoridad consolidada en Medina.", "en": "Consolidated power in Medina.", "ma": "عزز سلطة بالمدينة."}},
        {"id": 310, "category": "seerah", "question": {"es": "¿Años gobernó Ali?", "en": "Years Ali ruled?", "ma": "شحال حكم علي؟"}, "options": {"es": ["3", "Aproximadamente 5 años", "7", "10"], "en": ["3", "About 5 years", "7", "10"], "ma": ["3", "تقريبا 5 سنين", "7", "10"]}, "correct_answer": {"es": "Aproximadamente 5 años", "en": "About 5 years", "ma": "تقريبا 5 سنين"}, "difficulty": "medium", "explanation": {"es": "Ali gobernó unos 5 años.", "en": "Around 5 years.", "ma": "5 سنين تقريبا."}}
    ]

    for ov in overrides:
        found = False
        for i, q in enumerate(questions):
            if q['id'] == ov['id']:
                questions[i] = ov
                found = True
                break
        if not found:
            questions.append(ov)

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(questions, f, indent=2, ensure_ascii=False)
        
    print(len(questions))

if __name__ == '__main__':
    apply_fixes()
